// <auto-generated />
using System;
using BkpGasProcurementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BkpGasProcurementSystem.Migrations.BkpGasProcurementSystemDeliveries
{
    [DbContext(typeof(BkpGasProcurementSystemDeliveriesContext))]
    [Migration("20210731075134_addeddeliveries")]
    partial class addeddeliveries
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BkpGasProcurementSystem.Models.Deliveries", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ship_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("BkpGasProcurementSystem.Models.update_delivery", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DeliveriesID")
                        .HasColumnType("int");

                    b.Property<string>("message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("update_when")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("DeliveriesID");

                    b.ToTable("update_delivery");
                });

            modelBuilder.Entity("BkpGasProcurementSystem.Models.update_delivery", b =>
                {
                    b.HasOne("BkpGasProcurementSystem.Models.Deliveries", null)
                        .WithMany("delivery_history")
                        .HasForeignKey("DeliveriesID");
                });
#pragma warning restore 612, 618
        }
    }
}
